package com.huaqi.base.entity;

public class BmPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.p_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bm_position.description
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.id
     *
     * @return the value of bm_position.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.id
     *
     * @param id the value for bm_position.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.code
     *
     * @return the value of bm_position.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.code
     *
     * @param code the value for bm_position.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.name
     *
     * @return the value of bm_position.name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.name
     *
     * @param name the value for bm_position.name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.p_code
     *
     * @return the value of bm_position.p_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.p_code
     *
     * @param pCode the value for bm_position.p_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.level
     *
     * @return the value of bm_position.level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.level
     *
     * @param level the value for bm_position.level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bm_position.description
     *
     * @return the value of bm_position.description
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getDesc() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bm_position.description
     *
     * @param description the value for bm_position.description
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setDesc(String description) {
        this.description = description == null ? null : description.trim();
    }
}