package com.huaqi.base.entity;

import java.util.Date;

public class PmAboutUs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.logo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.app_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.company_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.company_address
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.company_email
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String companyEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_about_us.contract_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contractContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.id
     *
     * @return the value of pm_about_us.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.id
     *
     * @param id the value for pm_about_us.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.logo_url
     *
     * @return the value of pm_about_us.logo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.logo_url
     *
     * @param logoUrl the value for pm_about_us.logo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.app_name
     *
     * @return the value of pm_about_us.app_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.app_name
     *
     * @param appName the value for pm_about_us.app_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.company_name
     *
     * @return the value of pm_about_us.company_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.company_name
     *
     * @param companyName the value for pm_about_us.company_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.company_address
     *
     * @return the value of pm_about_us.company_address
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.company_address
     *
     * @param companyAddress the value for pm_about_us.company_address
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress == null ? null : companyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.company_email
     *
     * @return the value of pm_about_us.company_email
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCompanyEmail() {
        return companyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.company_email
     *
     * @param companyEmail the value for pm_about_us.company_email
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail == null ? null : companyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.create_time
     *
     * @return the value of pm_about_us.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.create_time
     *
     * @param createTime the value for pm_about_us.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.create_user
     *
     * @return the value of pm_about_us.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.create_user
     *
     * @param createUser the value for pm_about_us.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.update_time
     *
     * @return the value of pm_about_us.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.update_time
     *
     * @param updateTime the value for pm_about_us.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.update_user
     *
     * @return the value of pm_about_us.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.update_user
     *
     * @param updateUser the value for pm_about_us.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.is_deleted
     *
     * @return the value of pm_about_us.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.is_deleted
     *
     * @param isDeleted the value for pm_about_us.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_about_us.contract_content
     *
     * @return the value of pm_about_us.contract_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContractContent() {
        return contractContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_about_us.contract_content
     *
     * @param contractContent the value for pm_about_us.contract_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContractContent(String contractContent) {
        this.contractContent = contractContent == null ? null : contractContent.trim();
    }
}