package com.huaqi.base.entity;

import java.util.Date;

public class PmContestGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.group_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.group_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.age_min
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer ageMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.age_max
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer ageMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.gender
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.item_long
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String itemLong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_group.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.id
     *
     * @return the value of pm_contest_group.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.id
     *
     * @param id the value for pm_contest_group.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.contest_id
     *
     * @return the value of pm_contest_group.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.contest_id
     *
     * @param contestId the value for pm_contest_group.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(String contestId) {
        this.contestId = contestId == null ? null : contestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.group_code
     *
     * @return the value of pm_contest_group.group_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.group_code
     *
     * @param groupCode the value for pm_contest_group.group_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.group_name
     *
     * @return the value of pm_contest_group.group_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.group_name
     *
     * @param groupName the value for pm_contest_group.group_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.age_min
     *
     * @return the value of pm_contest_group.age_min
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getAgeMin() {
        return ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.age_min
     *
     * @param ageMin the value for pm_contest_group.age_min
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAgeMin(Integer ageMin) {
        this.ageMin = ageMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.age_max
     *
     * @return the value of pm_contest_group.age_max
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getAgeMax() {
        return ageMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.age_max
     *
     * @param ageMax the value for pm_contest_group.age_max
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAgeMax(Integer ageMax) {
        this.ageMax = ageMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.gender
     *
     * @return the value of pm_contest_group.gender
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.gender
     *
     * @param gender the value for pm_contest_group.gender
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.item_id
     *
     * @return the value of pm_contest_group.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.item_id
     *
     * @param itemId the value for pm_contest_group.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.item_long
     *
     * @return the value of pm_contest_group.item_long
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getItemLong() {
        return itemLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.item_long
     *
     * @param itemLong the value for pm_contest_group.item_long
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setItemLong(String itemLong) {
        this.itemLong = itemLong == null ? null : itemLong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.create_time
     *
     * @return the value of pm_contest_group.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.create_time
     *
     * @param createTime the value for pm_contest_group.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.create_user
     *
     * @return the value of pm_contest_group.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.create_user
     *
     * @param createUser the value for pm_contest_group.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.update_time
     *
     * @return the value of pm_contest_group.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.update_time
     *
     * @param updateTime the value for pm_contest_group.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.update_user
     *
     * @return the value of pm_contest_group.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.update_user
     *
     * @param updateUser the value for pm_contest_group.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_group.is_deleted
     *
     * @return the value of pm_contest_group.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_group.is_deleted
     *
     * @param isDeleted the value for pm_contest_group.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}