package com.huaqi.base.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PmContest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.contest_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contestCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private BigDecimal charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.signup_start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date signupStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.signup_end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date signupEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.match_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date matchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.sign_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer signType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.need_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer needAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.clerk_phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String clerkPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.contest_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contestContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.id
     *
     * @return the value of pm_contest.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.id
     *
     * @param id the value for pm_contest.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.contest_code
     *
     * @return the value of pm_contest.contest_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContestCode() {
        return contestCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.contest_code
     *
     * @param contestCode the value for pm_contest.contest_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestCode(String contestCode) {
        this.contestCode = contestCode == null ? null : contestCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.page_name
     *
     * @return the value of pm_contest.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.page_name
     *
     * @param pageName the value for pm_contest.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.item_id
     *
     * @return the value of pm_contest.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.item_id
     *
     * @param itemId the value for pm_contest.item_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.province_code
     *
     * @return the value of pm_contest.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.province_code
     *
     * @param provinceCode the value for pm_contest.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.city_code
     *
     * @return the value of pm_contest.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.city_code
     *
     * @param cityCode the value for pm_contest.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.region_code
     *
     * @return the value of pm_contest.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.region_code
     *
     * @param regionCode the value for pm_contest.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.district_code
     *
     * @return the value of pm_contest.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.district_code
     *
     * @param districtCode the value for pm_contest.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.address_detail
     *
     * @return the value of pm_contest.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.address_detail
     *
     * @param addressDetail the value for pm_contest.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.charge
     *
     * @return the value of pm_contest.charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public BigDecimal getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.charge
     *
     * @param charge the value for pm_contest.charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCharge(BigDecimal charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.signup_start_time
     *
     * @return the value of pm_contest.signup_start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getSignupStartTime() {
        return signupStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.signup_start_time
     *
     * @param signupStartTime the value for pm_contest.signup_start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setSignupStartTime(Date signupStartTime) {
        this.signupStartTime = signupStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.signup_end_time
     *
     * @return the value of pm_contest.signup_end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getSignupEndTime() {
        return signupEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.signup_end_time
     *
     * @param signupEndTime the value for pm_contest.signup_end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setSignupEndTime(Date signupEndTime) {
        this.signupEndTime = signupEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.match_time
     *
     * @return the value of pm_contest.match_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getMatchTime() {
        return matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.match_time
     *
     * @param matchTime the value for pm_contest.match_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setMatchTime(Date matchTime) {
        this.matchTime = matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.publish_time
     *
     * @return the value of pm_contest.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.publish_time
     *
     * @param publishTime the value for pm_contest.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.publish_status
     *
     * @return the value of pm_contest.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.publish_status
     *
     * @param publishStatus the value for pm_contest.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.sign_type
     *
     * @return the value of pm_contest.sign_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.sign_type
     *
     * @param signType the value for pm_contest.sign_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setSignType(Integer signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.charge_type
     *
     * @return the value of pm_contest.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.charge_type
     *
     * @param chargeType the value for pm_contest.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.need_audit
     *
     * @return the value of pm_contest.need_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getNeedAudit() {
        return needAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.need_audit
     *
     * @param needAudit the value for pm_contest.need_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setNeedAudit(Integer needAudit) {
        this.needAudit = needAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.clerk_phone
     *
     * @return the value of pm_contest.clerk_phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getClerkPhone() {
        return clerkPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.clerk_phone
     *
     * @param clerkPhone the value for pm_contest.clerk_phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setClerkPhone(String clerkPhone) {
        this.clerkPhone = clerkPhone == null ? null : clerkPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.contest_content
     *
     * @return the value of pm_contest.contest_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContestContent() {
        return contestContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.contest_content
     *
     * @param contestContent the value for pm_contest.contest_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestContent(String contestContent) {
        this.contestContent = contestContent == null ? null : contestContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.create_time
     *
     * @return the value of pm_contest.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.create_time
     *
     * @param createTime the value for pm_contest.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.create_user
     *
     * @return the value of pm_contest.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.create_user
     *
     * @param createUser the value for pm_contest.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.update_time
     *
     * @return the value of pm_contest.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.update_time
     *
     * @param updateTime the value for pm_contest.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.update_user
     *
     * @return the value of pm_contest.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.update_user
     *
     * @param updateUser the value for pm_contest.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest.is_deleted
     *
     * @return the value of pm_contest.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest.is_deleted
     *
     * @param isDeleted the value for pm_contest.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}