package com.huaqi.base.entity;

import java.util.Date;

public class PmContestSignup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long orderHeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.audit_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.audit_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.audit_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String auditUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.fefund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String fefundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.contest_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contestStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.score_level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String scoreLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.score
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_contest_signup.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.id
     *
     * @return the value of pm_contest_signup.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.id
     *
     * @param id the value for pm_contest_signup.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.order_header_id
     *
     * @return the value of pm_contest_signup.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getOrderHeaderId() {
        return orderHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.order_header_id
     *
     * @param orderHeaderId the value for pm_contest_signup.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setOrderHeaderId(Long orderHeaderId) {
        this.orderHeaderId = orderHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.user_id
     *
     * @return the value of pm_contest_signup.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.user_id
     *
     * @param userId the value for pm_contest_signup.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.contest_id
     *
     * @return the value of pm_contest_signup.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.contest_id
     *
     * @param contestId the value for pm_contest_signup.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(Long contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.audit_status
     *
     * @return the value of pm_contest_signup.audit_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.audit_status
     *
     * @param auditStatus the value for pm_contest_signup.audit_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.audit_time
     *
     * @return the value of pm_contest_signup.audit_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.audit_time
     *
     * @param auditTime the value for pm_contest_signup.audit_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.audit_user
     *
     * @return the value of pm_contest_signup.audit_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.audit_user
     *
     * @param auditUser the value for pm_contest_signup.audit_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.fefund_status
     *
     * @return the value of pm_contest_signup.fefund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getFefundStatus() {
        return fefundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.fefund_status
     *
     * @param fefundStatus the value for pm_contest_signup.fefund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setFefundStatus(String fefundStatus) {
        this.fefundStatus = fefundStatus == null ? null : fefundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.contest_status
     *
     * @return the value of pm_contest_signup.contest_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContestStatus() {
        return contestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.contest_status
     *
     * @param contestStatus the value for pm_contest_signup.contest_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestStatus(String contestStatus) {
        this.contestStatus = contestStatus == null ? null : contestStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.score_level
     *
     * @return the value of pm_contest_signup.score_level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getScoreLevel() {
        return scoreLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.score_level
     *
     * @param scoreLevel the value for pm_contest_signup.score_level
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setScoreLevel(String scoreLevel) {
        this.scoreLevel = scoreLevel == null ? null : scoreLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.score
     *
     * @return the value of pm_contest_signup.score
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.score
     *
     * @param score the value for pm_contest_signup.score
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.create_time
     *
     * @return the value of pm_contest_signup.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.create_time
     *
     * @param createTime the value for pm_contest_signup.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.create_user
     *
     * @return the value of pm_contest_signup.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.create_user
     *
     * @param createUser the value for pm_contest_signup.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.update_time
     *
     * @return the value of pm_contest_signup.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.update_time
     *
     * @param updateTime the value for pm_contest_signup.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.update_user
     *
     * @return the value of pm_contest_signup.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.update_user
     *
     * @param updateUser the value for pm_contest_signup.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_contest_signup.is_deleted
     *
     * @return the value of pm_contest_signup.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_contest_signup.is_deleted
     *
     * @param isDeleted the value for pm_contest_signup.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}