package com.huaqi.base.entity;

import java.util.Date;

public class PmHomeBannerConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.home_page_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long homePageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.banner_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String bannerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.jump_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String jumpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_home_banner_config.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.id
     *
     * @return the value of pm_home_banner_config.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.id
     *
     * @param id the value for pm_home_banner_config.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.home_page_id
     *
     * @return the value of pm_home_banner_config.home_page_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getHomePageId() {
        return homePageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.home_page_id
     *
     * @param homePageId the value for pm_home_banner_config.home_page_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setHomePageId(Long homePageId) {
        this.homePageId = homePageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.rank
     *
     * @return the value of pm_home_banner_config.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.rank
     *
     * @param rank the value for pm_home_banner_config.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.page_name
     *
     * @return the value of pm_home_banner_config.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.page_name
     *
     * @param pageName the value for pm_home_banner_config.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.start_time
     *
     * @return the value of pm_home_banner_config.start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.start_time
     *
     * @param startTime the value for pm_home_banner_config.start_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.end_time
     *
     * @return the value of pm_home_banner_config.end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.end_time
     *
     * @param endTime the value for pm_home_banner_config.end_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.banner_url
     *
     * @return the value of pm_home_banner_config.banner_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getBannerUrl() {
        return bannerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.banner_url
     *
     * @param bannerUrl the value for pm_home_banner_config.banner_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl == null ? null : bannerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.jump_url
     *
     * @return the value of pm_home_banner_config.jump_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getJumpUrl() {
        return jumpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.jump_url
     *
     * @param jumpUrl the value for pm_home_banner_config.jump_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setJumpUrl(String jumpUrl) {
        this.jumpUrl = jumpUrl == null ? null : jumpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.create_time
     *
     * @return the value of pm_home_banner_config.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.create_time
     *
     * @param createTime the value for pm_home_banner_config.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.create_user
     *
     * @return the value of pm_home_banner_config.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.create_user
     *
     * @param createUser the value for pm_home_banner_config.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.update_time
     *
     * @return the value of pm_home_banner_config.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.update_time
     *
     * @param updateTime the value for pm_home_banner_config.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.update_user
     *
     * @return the value of pm_home_banner_config.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.update_user
     *
     * @param updateUser the value for pm_home_banner_config.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_home_banner_config.is_deleted
     *
     * @return the value of pm_home_banner_config.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_home_banner_config.is_deleted
     *
     * @param isDeleted the value for pm_home_banner_config.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}