package com.huaqi.base.entity;

import java.util.Date;

public class PmInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.is_top
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.information_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String informationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.information_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String informationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.publisher
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.is_show
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_information.information_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String informationContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.id
     *
     * @return the value of pm_information.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.id
     *
     * @param id the value for pm_information.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.is_top
     *
     * @return the value of pm_information.is_top
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.is_top
     *
     * @param isTop the value for pm_information.is_top
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.rank
     *
     * @return the value of pm_information.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.rank
     *
     * @param rank the value for pm_information.rank
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.information_name
     *
     * @return the value of pm_information.information_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getInformationName() {
        return informationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.information_name
     *
     * @param informationName the value for pm_information.information_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setInformationName(String informationName) {
        this.informationName = informationName == null ? null : informationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.information_code
     *
     * @return the value of pm_information.information_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getInformationCode() {
        return informationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.information_code
     *
     * @param informationCode the value for pm_information.information_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setInformationCode(String informationCode) {
        this.informationCode = informationCode == null ? null : informationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.publish_time
     *
     * @return the value of pm_information.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.publish_time
     *
     * @param publishTime the value for pm_information.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.publisher
     *
     * @return the value of pm_information.publisher
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.publisher
     *
     * @param publisher the value for pm_information.publisher
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.user_code
     *
     * @return the value of pm_information.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.user_code
     *
     * @param userCode the value for pm_information.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.is_show
     *
     * @return the value of pm_information.is_show
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.is_show
     *
     * @param isShow the value for pm_information.is_show
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.create_time
     *
     * @return the value of pm_information.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.create_time
     *
     * @param createTime the value for pm_information.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.create_user
     *
     * @return the value of pm_information.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.create_user
     *
     * @param createUser the value for pm_information.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.update_time
     *
     * @return the value of pm_information.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.update_time
     *
     * @param updateTime the value for pm_information.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.update_user
     *
     * @return the value of pm_information.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.update_user
     *
     * @param updateUser the value for pm_information.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.is_deleted
     *
     * @return the value of pm_information.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.is_deleted
     *
     * @param isDeleted the value for pm_information.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_information.information_content
     *
     * @return the value of pm_information.information_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getInformationContent() {
        return informationContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_information.information_content
     *
     * @param informationContent the value for pm_information.information_content
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setInformationContent(String informationContent) {
        this.informationContent = informationContent == null ? null : informationContent.trim();
    }
}