package com.huaqi.base.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PmOrderRefund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private BigDecimal totalCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String weixinOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.refund_wx_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String refundWxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.refund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_order_refund.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.id
     *
     * @return the value of pm_order_refund.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.id
     *
     * @param id the value for pm_order_refund.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.contest_id
     *
     * @return the value of pm_order_refund.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.contest_id
     *
     * @param contestId the value for pm_order_refund.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(Long contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.user_id
     *
     * @return the value of pm_order_refund.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.user_id
     *
     * @param userId the value for pm_order_refund.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.total_charge
     *
     * @return the value of pm_order_refund.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public BigDecimal getTotalCharge() {
        return totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.total_charge
     *
     * @param totalCharge the value for pm_order_refund.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setTotalCharge(BigDecimal totalCharge) {
        this.totalCharge = totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.weixin_order_id
     *
     * @return the value of pm_order_refund.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getWeixinOrderId() {
        return weixinOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.weixin_order_id
     *
     * @param weixinOrderId the value for pm_order_refund.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setWeixinOrderId(String weixinOrderId) {
        this.weixinOrderId = weixinOrderId == null ? null : weixinOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.refund_wx_id
     *
     * @return the value of pm_order_refund.refund_wx_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getRefundWxId() {
        return refundWxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.refund_wx_id
     *
     * @param refundWxId the value for pm_order_refund.refund_wx_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRefundWxId(String refundWxId) {
        this.refundWxId = refundWxId == null ? null : refundWxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.refund_status
     *
     * @return the value of pm_order_refund.refund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.refund_status
     *
     * @param refundStatus the value for pm_order_refund.refund_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.create_time
     *
     * @return the value of pm_order_refund.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.create_time
     *
     * @param createTime the value for pm_order_refund.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.create_user
     *
     * @return the value of pm_order_refund.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.create_user
     *
     * @param createUser the value for pm_order_refund.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.update_time
     *
     * @return the value of pm_order_refund.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.update_time
     *
     * @param updateTime the value for pm_order_refund.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.update_user
     *
     * @return the value of pm_order_refund.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.update_user
     *
     * @param updateUser the value for pm_order_refund.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_order_refund.is_deleted
     *
     * @return the value of pm_order_refund.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_order_refund.is_deleted
     *
     * @param isDeleted the value for pm_order_refund.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}