package com.huaqi.base.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PmSignupOrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long orderHeaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.contest_group_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long contestGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.item_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private BigDecimal itemCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_item.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.id
     *
     * @return the value of pm_signup_order_item.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.id
     *
     * @param id the value for pm_signup_order_item.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.order_header_id
     *
     * @return the value of pm_signup_order_item.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getOrderHeaderId() {
        return orderHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.order_header_id
     *
     * @param orderHeaderId the value for pm_signup_order_item.order_header_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setOrderHeaderId(Long orderHeaderId) {
        this.orderHeaderId = orderHeaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.contest_id
     *
     * @return the value of pm_signup_order_item.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.contest_id
     *
     * @param contestId the value for pm_signup_order_item.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(Long contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.contest_group_id
     *
     * @return the value of pm_signup_order_item.contest_group_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getContestGroupId() {
        return contestGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.contest_group_id
     *
     * @param contestGroupId the value for pm_signup_order_item.contest_group_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestGroupId(Long contestGroupId) {
        this.contestGroupId = contestGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.item_charge
     *
     * @return the value of pm_signup_order_item.item_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public BigDecimal getItemCharge() {
        return itemCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.item_charge
     *
     * @param itemCharge the value for pm_signup_order_item.item_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setItemCharge(BigDecimal itemCharge) {
        this.itemCharge = itemCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.charge_type
     *
     * @return the value of pm_signup_order_item.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.charge_type
     *
     * @param chargeType the value for pm_signup_order_item.charge_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.create_time
     *
     * @return the value of pm_signup_order_item.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.create_time
     *
     * @param createTime the value for pm_signup_order_item.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.create_user
     *
     * @return the value of pm_signup_order_item.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.create_user
     *
     * @param createUser the value for pm_signup_order_item.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.update_time
     *
     * @return the value of pm_signup_order_item.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.update_time
     *
     * @param updateTime the value for pm_signup_order_item.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.update_user
     *
     * @return the value of pm_signup_order_item.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.update_user
     *
     * @param updateUser the value for pm_signup_order_item.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_item.is_deleted
     *
     * @return the value of pm_signup_order_item.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_item.is_deleted
     *
     * @param isDeleted the value for pm_signup_order_item.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}