package com.huaqi.base.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PmSignupOrderHeader {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private BigDecimal totalCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String weixinOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.order_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_signup_order_header.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.id
     *
     * @return the value of pm_signup_order_header.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.id
     *
     * @param id the value for pm_signup_order_header.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.contest_id
     *
     * @return the value of pm_signup_order_header.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.contest_id
     *
     * @param contestId the value for pm_signup_order_header.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(String contestId) {
        this.contestId = contestId == null ? null : contestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.total_charge
     *
     * @return the value of pm_signup_order_header.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public BigDecimal getTotalCharge() {
        return totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.total_charge
     *
     * @param totalCharge the value for pm_signup_order_header.total_charge
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setTotalCharge(BigDecimal totalCharge) {
        this.totalCharge = totalCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.weixin_order_id
     *
     * @return the value of pm_signup_order_header.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getWeixinOrderId() {
        return weixinOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.weixin_order_id
     *
     * @param weixinOrderId the value for pm_signup_order_header.weixin_order_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setWeixinOrderId(String weixinOrderId) {
        this.weixinOrderId = weixinOrderId == null ? null : weixinOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.order_status
     *
     * @return the value of pm_signup_order_header.order_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.order_status
     *
     * @param orderStatus the value for pm_signup_order_header.order_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.create_time
     *
     * @return the value of pm_signup_order_header.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.create_time
     *
     * @param createTime the value for pm_signup_order_header.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.create_user
     *
     * @return the value of pm_signup_order_header.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.create_user
     *
     * @param createUser the value for pm_signup_order_header.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.update_time
     *
     * @return the value of pm_signup_order_header.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.update_time
     *
     * @param updateTime the value for pm_signup_order_header.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.update_user
     *
     * @return the value of pm_signup_order_header.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.update_user
     *
     * @param updateUser the value for pm_signup_order_header.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_signup_order_header.is_deleted
     *
     * @return the value of pm_signup_order_header.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_signup_order_header.is_deleted
     *
     * @param isDeleted the value for pm_signup_order_header.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}