package com.huaqi.base.entity;

import java.util.Date;

public class PmSpecial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.special_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String specialCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.contest_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer contestCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer publishStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.id
     *
     * @return the value of pm_special.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.id
     *
     * @param id the value for pm_special.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.page_name
     *
     * @return the value of pm_special.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.page_name
     *
     * @param pageName the value for pm_special.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.special_code
     *
     * @return the value of pm_special.special_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getSpecialCode() {
        return specialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.special_code
     *
     * @param specialCode the value for pm_special.special_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setSpecialCode(String specialCode) {
        this.specialCode = specialCode == null ? null : specialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.contest_count
     *
     * @return the value of pm_special.contest_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getContestCount() {
        return contestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.contest_count
     *
     * @param contestCount the value for pm_special.contest_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestCount(Integer contestCount) {
        this.contestCount = contestCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.publish_time
     *
     * @return the value of pm_special.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.publish_time
     *
     * @param publishTime the value for pm_special.publish_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.publish_status
     *
     * @return the value of pm_special.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.publish_status
     *
     * @param publishStatus the value for pm_special.publish_status
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPublishStatus(Integer publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.create_time
     *
     * @return the value of pm_special.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.create_time
     *
     * @param createTime the value for pm_special.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.create_user
     *
     * @return the value of pm_special.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.create_user
     *
     * @param createUser the value for pm_special.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.update_time
     *
     * @return the value of pm_special.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.update_time
     *
     * @param updateTime the value for pm_special.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.update_user
     *
     * @return the value of pm_special.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.update_user
     *
     * @param updateUser the value for pm_special.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special.is_deleted
     *
     * @return the value of pm_special.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special.is_deleted
     *
     * @param isDeleted the value for pm_special.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}