package com.huaqi.base.entity;

import java.util.Date;

public class PmSpecialContestRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long contestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_special_contest_relation.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.id
     *
     * @return the value of pm_special_contest_relation.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.id
     *
     * @param id the value for pm_special_contest_relation.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.page_name
     *
     * @return the value of pm_special_contest_relation.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.page_name
     *
     * @param pageName the value for pm_special_contest_relation.page_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPageName(Long pageName) {
        this.pageName = pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.contest_id
     *
     * @return the value of pm_special_contest_relation.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.contest_id
     *
     * @param contestId the value for pm_special_contest_relation.contest_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setContestId(Long contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.create_time
     *
     * @return the value of pm_special_contest_relation.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.create_time
     *
     * @param createTime the value for pm_special_contest_relation.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.create_user
     *
     * @return the value of pm_special_contest_relation.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.create_user
     *
     * @param createUser the value for pm_special_contest_relation.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.update_time
     *
     * @return the value of pm_special_contest_relation.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.update_time
     *
     * @param updateTime the value for pm_special_contest_relation.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.update_user
     *
     * @return the value of pm_special_contest_relation.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.update_user
     *
     * @param updateUser the value for pm_special_contest_relation.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_special_contest_relation.is_deleted
     *
     * @return the value of pm_special_contest_relation.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_special_contest_relation.is_deleted
     *
     * @param isDeleted the value for pm_special_contest_relation.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}