package com.huaqi.base.entity;

import java.util.Date;

public class UmPlayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.club_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long clubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.player_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String playerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.player_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.age
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer genderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.id_up_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String idUpUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.id_back_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String idBackUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.qr_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String qrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.qr_code_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String qrCodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_player.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.id
     *
     * @return the value of um_player.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.id
     *
     * @param id the value for um_player.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.club_id
     *
     * @return the value of um_player.club_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.club_id
     *
     * @param clubId the value for um_player.club_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setClubId(Long clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.user_id
     *
     * @return the value of um_player.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.user_id
     *
     * @param userId the value for um_player.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.player_code
     *
     * @return the value of um_player.player_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPlayerCode() {
        return playerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.player_code
     *
     * @param playerCode the value for um_player.player_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPlayerCode(String playerCode) {
        this.playerCode = playerCode == null ? null : playerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.player_name
     *
     * @return the value of um_player.player_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.player_name
     *
     * @param playerName the value for um_player.player_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.phone
     *
     * @return the value of um_player.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.phone
     *
     * @param phone the value for um_player.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.age
     *
     * @return the value of um_player.age
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.age
     *
     * @param age the value for um_player.age
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.gender_code
     *
     * @return the value of um_player.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getGenderCode() {
        return genderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.gender_code
     *
     * @param genderCode the value for um_player.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setGenderCode(Integer genderCode) {
        this.genderCode = genderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.photo_url
     *
     * @return the value of um_player.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.photo_url
     *
     * @param photoUrl the value for um_player.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.id_up_url
     *
     * @return the value of um_player.id_up_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getIdUpUrl() {
        return idUpUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.id_up_url
     *
     * @param idUpUrl the value for um_player.id_up_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIdUpUrl(String idUpUrl) {
        this.idUpUrl = idUpUrl == null ? null : idUpUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.id_back_url
     *
     * @return the value of um_player.id_back_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getIdBackUrl() {
        return idBackUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.id_back_url
     *
     * @param idBackUrl the value for um_player.id_back_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIdBackUrl(String idBackUrl) {
        this.idBackUrl = idBackUrl == null ? null : idBackUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.qr_code
     *
     * @return the value of um_player.qr_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.qr_code
     *
     * @param qrCode the value for um_player.qr_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.qr_code_url
     *
     * @return the value of um_player.qr_code_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getQrCodeUrl() {
        return qrCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.qr_code_url
     *
     * @param qrCodeUrl the value for um_player.qr_code_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setQrCodeUrl(String qrCodeUrl) {
        this.qrCodeUrl = qrCodeUrl == null ? null : qrCodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.province_code
     *
     * @return the value of um_player.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.province_code
     *
     * @param provinceCode the value for um_player.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.city_code
     *
     * @return the value of um_player.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.city_code
     *
     * @param cityCode the value for um_player.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.region_code
     *
     * @return the value of um_player.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.region_code
     *
     * @param regionCode the value for um_player.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.district_code
     *
     * @return the value of um_player.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.district_code
     *
     * @param districtCode the value for um_player.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.address_detail
     *
     * @return the value of um_player.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.address_detail
     *
     * @param addressDetail the value for um_player.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.create_time
     *
     * @return the value of um_player.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.create_time
     *
     * @param createTime the value for um_player.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.create_user
     *
     * @return the value of um_player.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.create_user
     *
     * @param createUser the value for um_player.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.update_time
     *
     * @return the value of um_player.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.update_time
     *
     * @param updateTime the value for um_player.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.update_user
     *
     * @return the value of um_player.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.update_user
     *
     * @param updateUser the value for um_player.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_player.is_deleted
     *
     * @return the value of um_player.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_player.is_deleted
     *
     * @param isDeleted the value for um_player.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}