package com.huaqi.base.entity;

import java.util.Date;

public class UmUserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_login.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.id
     *
     * @return the value of um_user_login.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.id
     *
     * @param id the value for um_user_login.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.user_id
     *
     * @return the value of um_user_login.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.user_id
     *
     * @param userId the value for um_user_login.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.create_time
     *
     * @return the value of um_user_login.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.create_time
     *
     * @param createTime the value for um_user_login.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.create_user
     *
     * @return the value of um_user_login.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.create_user
     *
     * @param createUser the value for um_user_login.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.update_time
     *
     * @return the value of um_user_login.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.update_time
     *
     * @param updateTime the value for um_user_login.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.update_user
     *
     * @return the value of um_user_login.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.update_user
     *
     * @param updateUser the value for um_user_login.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_login.is_deleted
     *
     * @return the value of um_user_login.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_login.is_deleted
     *
     * @param isDeleted the value for um_user_login.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}