package com.huaqi.base.entity;

import java.util.Date;

public class UmUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.weixin_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String weixinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.user_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.nick_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.user_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.password
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer genderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String addressDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.player_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer playerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.is_lock
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.social_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String socialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.corporation_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String corporationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.club_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.mail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.business_pic
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String businessPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.reg_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.id
     *
     * @return the value of um_user.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.id
     *
     * @param id the value for um_user.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.weixin_id
     *
     * @return the value of um_user.weixin_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getWeixinId() {
        return weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.weixin_id
     *
     * @param weixinId the value for um_user.weixin_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setWeixinId(String weixinId) {
        this.weixinId = weixinId == null ? null : weixinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.user_type
     *
     * @return the value of um_user.user_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.user_type
     *
     * @param userType the value for um_user.user_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.user_code
     *
     * @return the value of um_user.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.user_code
     *
     * @param userCode the value for um_user.user_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.nick_name
     *
     * @return the value of um_user.nick_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.nick_name
     *
     * @param nickName the value for um_user.nick_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.user_name
     *
     * @return the value of um_user.user_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.user_name
     *
     * @param userName the value for um_user.user_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.phone
     *
     * @return the value of um_user.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.phone
     *
     * @param phone the value for um_user.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.password
     *
     * @return the value of um_user.password
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.password
     *
     * @param password the value for um_user.password
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.photo_url
     *
     * @return the value of um_user.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.photo_url
     *
     * @param photoUrl the value for um_user.photo_url
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.gender_code
     *
     * @return the value of um_user.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getGenderCode() {
        return genderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.gender_code
     *
     * @param genderCode the value for um_user.gender_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setGenderCode(Integer genderCode) {
        this.genderCode = genderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.province_code
     *
     * @return the value of um_user.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.province_code
     *
     * @param provinceCode the value for um_user.province_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.city_code
     *
     * @return the value of um_user.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.city_code
     *
     * @param cityCode the value for um_user.city_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.region_code
     *
     * @return the value of um_user.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.region_code
     *
     * @param regionCode the value for um_user.region_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.district_code
     *
     * @return the value of um_user.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.district_code
     *
     * @param districtCode the value for um_user.district_code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode == null ? null : districtCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.address_detail
     *
     * @return the value of um_user.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.address_detail
     *
     * @param addressDetail the value for um_user.address_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail == null ? null : addressDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.player_count
     *
     * @return the value of um_user.player_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getPlayerCount() {
        return playerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.player_count
     *
     * @param playerCount the value for um_user.player_count
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPlayerCount(Integer playerCount) {
        this.playerCount = playerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.is_lock
     *
     * @return the value of um_user.is_lock
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.is_lock
     *
     * @param isLock the value for um_user.is_lock
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsLock(Integer isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.social_id
     *
     * @return the value of um_user.social_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getSocialId() {
        return socialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.social_id
     *
     * @param socialId the value for um_user.social_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setSocialId(String socialId) {
        this.socialId = socialId == null ? null : socialId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.corporation_name
     *
     * @return the value of um_user.corporation_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCorporationName() {
        return corporationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.corporation_name
     *
     * @param corporationName the value for um_user.corporation_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCorporationName(String corporationName) {
        this.corporationName = corporationName == null ? null : corporationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.code
     *
     * @return the value of um_user.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.code
     *
     * @param code the value for um_user.code
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.club_name
     *
     * @return the value of um_user.club_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.club_name
     *
     * @param clubName the value for um_user.club_name
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.mail
     *
     * @return the value of um_user.mail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.mail
     *
     * @param mail the value for um_user.mail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.business_pic
     *
     * @return the value of um_user.business_pic
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getBusinessPic() {
        return businessPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.business_pic
     *
     * @param businessPic the value for um_user.business_pic
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setBusinessPic(String businessPic) {
        this.businessPic = businessPic == null ? null : businessPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.reg_time
     *
     * @return the value of um_user.reg_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.reg_time
     *
     * @param regTime the value for um_user.reg_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.create_time
     *
     * @return the value of um_user.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.create_time
     *
     * @param createTime the value for um_user.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.create_user
     *
     * @return the value of um_user.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.create_user
     *
     * @param createUser the value for um_user.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.update_time
     *
     * @return the value of um_user.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.update_time
     *
     * @param updateTime the value for um_user.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.update_user
     *
     * @return the value of um_user.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.update_user
     *
     * @param updateUser the value for um_user.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user.is_deleted
     *
     * @return the value of um_user.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user.is_deleted
     *
     * @param isDeleted the value for um_user.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}