package com.huaqi.base.entity;

import java.util.Date;

public class UmUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.message_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Integer messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.message_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String messageDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.validate_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date validateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column um_user_message.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.id
     *
     * @return the value of um_user_message.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.id
     *
     * @param id the value for um_user_message.id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.user_id
     *
     * @return the value of um_user_message.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.user_id
     *
     * @param userId the value for um_user_message.user_id
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.phone
     *
     * @return the value of um_user_message.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.phone
     *
     * @param phone the value for um_user_message.phone
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.message_type
     *
     * @return the value of um_user_message.message_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.message_type
     *
     * @param messageType the value for um_user_message.message_type
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.message_detail
     *
     * @return the value of um_user_message.message_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getMessageDetail() {
        return messageDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.message_detail
     *
     * @param messageDetail the value for um_user_message.message_detail
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setMessageDetail(String messageDetail) {
        this.messageDetail = messageDetail == null ? null : messageDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.validate_time
     *
     * @return the value of um_user_message.validate_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getValidateTime() {
        return validateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.validate_time
     *
     * @param validateTime the value for um_user_message.validate_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setValidateTime(Date validateTime) {
        this.validateTime = validateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.create_time
     *
     * @return the value of um_user_message.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.create_time
     *
     * @param createTime the value for um_user_message.create_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.create_user
     *
     * @return the value of um_user_message.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.create_user
     *
     * @param createUser the value for um_user_message.create_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.update_time
     *
     * @return the value of um_user_message.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.update_time
     *
     * @param updateTime the value for um_user_message.update_time
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.update_user
     *
     * @return the value of um_user_message.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.update_user
     *
     * @param updateUser the value for um_user_message.update_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column um_user_message.is_deleted
     *
     * @return the value of um_user_message.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column um_user_message.is_deleted
     *
     * @param isDeleted the value for um_user_message.is_deleted
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}