package com.huaqi.web.dao;

import com.huaqi.base.entity.BmPosition;

public interface BmPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(BmPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(BmPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    BmPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(BmPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bm_position
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(BmPosition record);
}