package com.huaqi.web.dao;

import com.huaqi.base.entity.PmAboutUs;

public interface PmAboutUsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmAboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmAboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmAboutUs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmAboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PmAboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_about_us
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmAboutUs record);
}