package com.huaqi.web.dao;

import com.huaqi.base.entity.PmClubAudit;

public interface PmClubAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmClubAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmClubAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmClubAudit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmClubAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_club_audit
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmClubAudit record);
}