package com.huaqi.web.dao;

import com.huaqi.base.entity.PmContest;

public interface PmContestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmContest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmContest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmContest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmContest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmContest record);
}