package com.huaqi.web.dao;

import com.huaqi.base.entity.PmContestSignup;

public interface PmContestSignupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmContestSignup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmContestSignup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmContestSignup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmContestSignup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_signup
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmContestSignup record);
}