package com.huaqi.web.dao;

import com.huaqi.base.entity.PmContestGroup;

public interface PmContestGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmContestGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmContestGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmContestGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmContestGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_contest_group
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmContestGroup record);
}