package com.huaqi.web.dao;

import com.huaqi.base.entity.PmHomeBannerConfig;

public interface PmHomeBannerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmHomeBannerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmHomeBannerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmHomeBannerConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmHomeBannerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_banner_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmHomeBannerConfig record);
}