package com.huaqi.web.dao;

import com.huaqi.base.entity.PmHomeAdConfig;

public interface PmHomeAdConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmHomeAdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmHomeAdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmHomeAdConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmHomeAdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_ad_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmHomeAdConfig record);
}