package com.huaqi.web.dao;

import com.huaqi.base.entity.PmHomeInfoConfig;

public interface PmHomeInfoConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmHomeInfoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmHomeInfoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmHomeInfoConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmHomeInfoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_home_info_config
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmHomeInfoConfig record);
}