package com.huaqi.web.dao;

import com.huaqi.base.entity.PmInformation;

public interface PmInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmInformation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(PmInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_information
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmInformation record);
}