package com.huaqi.web.dao;

import com.huaqi.base.entity.PmSignupOrderHeader;

public interface PmSignupOrderHeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmSignupOrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmSignupOrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmSignupOrderHeader selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmSignupOrderHeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_header
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmSignupOrderHeader record);
}