package com.huaqi.web.dao;

import com.huaqi.base.entity.PmSignupOrderItem;

public interface PmSignupOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmSignupOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmSignupOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmSignupOrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmSignupOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_signup_order_item
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmSignupOrderItem record);
}