package com.huaqi.web.dao;

import com.huaqi.base.entity.PmSpecial;

public interface PmSpecialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(PmSpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(PmSpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    PmSpecial selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(PmSpecial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_special
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(PmSpecial record);
}