package com.huaqi.web.dao;

import com.huaqi.base.entity.UmUserMessage;

public interface UmUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(UmUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(UmUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    UmUserMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(UmUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_message
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(UmUserMessage record);
}