package com.huaqi.web.dao;

import com.huaqi.base.entity.UmUser;

public interface UmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(UmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(UmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    UmUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(UmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(UmUser record);
}