package com.huaqi.web.dao;

import com.huaqi.base.entity.UmUserLogin;

public interface UmUserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insert(UmUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int insertSelective(UmUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    UmUserLogin selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKeySelective(UmUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table um_user_login
     *
     * @mbggenerated Thu Jan 02 11:58:20 CST 2020
     */
    int updateByPrimaryKey(UmUserLogin record);
}